### ISSUE TITLE
Add Sorbet for Type Checking

### ISSUE THREAD

**Issue by rzhade3** [github/hackerone-client#6]
@rzhade3:

We should consider adding [Sorbet type checking](https://sorbet.org/). 

---

_Transferred from https://github.com/oreoshake/hackerone-client/issues/66_

**Comment by boveus** [comment]
We discussed this and the cost benefit of this does not seem worth it.  While we would gain some type safety, it doesn't seem like we would gain much compared to how much work this would require.
